### ISSUE TITLE
Token contract is empty

### ISSUE THREAD

**Issue by vbaranov** [oraclesorg/treasury#2]
Token contract source code is empty: https://github.com/oraclesorg/treasury/blob/master/contracts/TestToken.sol.
Let's create extension of mintable token with `tokenDepositEvent ` at transfer method.

**Comment by lorien** [comment]
Why mintable? Mintable or not does not affect on transfer method. I suggest just StandardToken.

**Comment by igorbarinov** [comment]
@vbaranov we will create all tokens (252,460,800) on the right side before the token sale start. After crowd sale ends we will send exact amount of sold tokens in coins from multisig to the treasury. Buyers will exchange tokens to coins. Unsold tokens will be on the contract of the right side of the bridge. 

I don't understand either why do we need mintable token here.

**Comment by vbaranov** [comment]
Maybe, it's my misunderstanding. Let me explain.

I make tests for bridge this way: 
* I create mintable token
* mint hardcap of crowdsale to master of ceremony address
* join mintable token to the right side of the bridge
* tokens are transfered to user address from master of ceremony during buying

How to fill master of ceremony balance without minting?

**Comment by igorbarinov** [comment]
why do we need to mint token? we can specify the number of tokens and owner (master of ceremony) as a const in StandardToken, right?

**Comment by lorien** [comment]
> How to fill master of ceremony balance without minting?

Just put desired number of tokens into `balances[msg.sender]` in the Token constructor. Like that done in TestToken: https://github.com/oraclesorg/treasury/blob/master/contracts/TestToken.sol#L12

**Comment by vbaranov** [comment]
Ok, I see. Thanks.
