### ISSUE TITLE
Binding token and treasury.

### ISSUE THREAD

**Issue by lorien** [oraclesorg/treasury#3]
At the moment Treasury contract has `initialize` method that sets up token address and token/ether excachange rate. That implies that token contract was created before treasury. But token contract also should know address of treasury contract to send transfer signal if tokens are transferring to the treasury address.
Should token contract also have initialize method?

**Comment by vbaranov** [comment]
Yes, I think so. Maybe, let’s call it setTreasury? And owner can set it multiple times. And add public property treasury, which will store treasury address?

**Comment by igorbarinov** [comment]
@akolotov what do you think?

**Comment by lorien** [comment]
I've implemented setTreasury method so far. Will update it if you suggest another solution.
