### ISSUE TITLE
calling tokenDepositEvent from transferFrom

### ISSUE THREAD

**Issue by lorien** [oraclesorg/treasury#4]
Now if tokens are sent to treasury (with `transfer` method) token calls `tokenDepositEvent` from treasury contract.
I think `tokenDepositEvent` should be called also if tokens are sent with `transferFrom` method. What do you think?

**Comment by vbaranov** [comment]
For me too. I think, this event should be spread to both transfer methods.

**Comment by lorien** [comment]
```
function transferFrom(address _from, address _to, uint256 _value) public returns (bool) {
```
I am not sure who should receive tokens if `transferFrom` transfers tokens to treasury.:

* `msg.sender`?
* `_from`?

**Comment by lorien** [comment]
Another possible solution of transferFrom issue: just restrict transferFrom to send tokens to treasury address.

**Comment by vbaranov** [comment]
Good idea with restriction

**Comment by lorien** [comment]
Done in 5a0546bbd5949bbe08d74931d459ea6b415657cf
