### ISSUE TITLE
Transfer should be available from right side bridge address during crowdsale

### ISSUE THREAD

**Issue by vbaranov** [oraclesorg/treasury#8]
For now transfer is disabled unill we setTreasury for all addresses. But during crowdsale we need to transfer tokens from the right side of the bridge address to any address. Let's create bridge address in the token constructor, and allow transfer when msg.sender ==  bridge, if setTreasury wasn't called yet

**Comment by lorien** [comment]
I've implemented this feature. I'll add few more tests today/tomorrow.

**Comment by lorien** [comment]
Done. I've add bunch of new tests.
Related commits:
fcc5f327879944e5fe2c517e88d6e12367ad5125
c0713a0bfae31831b9f5daf3a771e9f5bbf8af97
1ab4c5861277f6f7a08c8cd7875ff003eb8f3aae
90704578788703a1ad98d8c295ce179e9381d0c2
